# Generated by Django 3.2.4 on 2022-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-created_date'], 'verbose_name': 'اطلاعات کاربر', 'verbose_name_plural': 'اطلاعات کاربر'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
