# Generated by Django 3.2.4 on 2022-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220426_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
