# Generated by Django 3.2.4 on 2022-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220426_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='accounts/default.png', upload_to='accounts/', verbose_name='آواتار'),
        ),
    ]
