# Generated by Django 3.2.4 on 2022-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-created_date'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='papercategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='papertag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.ManyToManyField(to='guide.PaperCategory', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='counted_views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='published_date',
            field=models.DateTimeField(null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(to='guide.PaperTag', verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=300, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='papercategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='papertag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام برچسب'),
        ),
    ]
