# Generated by Django 3.2.4 on 2022-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='شناسه خرید'),
        ),
    ]
