# Generated by Django 3.2.4 on 2022-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='مجموع قیمت'),
        ),
    ]
