# Generated by Django 3.2.4 on 2022-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='شناسه خرید'),
        ),
    ]
