# Generated by Django 3.2.4 on 2022-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_auto_20220429_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-created_date'], 'verbose_name': 'محصولات سفارش', 'verbose_name_plural': 'محصولات سفارش'},
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, to='bookstore.OrderProduct', verbose_name='محصولات'),
        ),
    ]
